'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Centaurus.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Achievements are intented to show off about what players have achieved by using it and playing I.G.I.-2. It helps to grow the reputation among public, and proves how much the player is dedicated &amp; stronger to play.
        '''
        '''There are three types of achievements featured in Centaurus, viz. Join Records, ChatUp Records, Login Records.
        '''
        ''' • The Join Records achievement is dependent upon how many times you joins the game to play. Once you reach the Bronze badge (3rd from the last legend ones), you may thereafter cha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property achievementHelp() As String
            Get
                Return ResourceManager.GetString("achievementHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you do not agree to any of the terms written underneath, please immediately stop using Centaurus. The author will not take any responsibilities or will not be liable for any damages caused by the system.
        '''
        '''I respect the following rules and conditions before starting to use Centaurus:
        '''
        '''1. Using any abusive name will not be tolerated.
        '''2. On the first run, Centaurus collects some necessary performance data, please allow it (notice system data, not personal).
        '''3. Centaurus must have rights to replace I.G [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property agreement() As String
            Get
                Return ResourceManager.GetString("agreement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Aim_map() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Aim_map", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ammo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ammo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before starting and chatting among buddies, you must have some intuition about communicating rules &amp; regulations listed below:
        '''
        '''  1. The time is synchronized with GMT+5:30 (Indian Standard Time), so, the time might be different for your country if you belongs to somewhere else.
        '''
        '''  2. This is a public chat, so chat smart &amp; do not use any abusive language or any hate speech.
        '''
        '''  3. Do not spam in chat to disturb anyone if you have nothing relevant to do with corresponding discussion(s).
        '''
        '''  4. You are a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property chatRules() As String
            Get
                Return ResourceManager.GetString("chatRules", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chinesetemple() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chinesetemple", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chintemple2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chintemple2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Console() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Console", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DeepInMines() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DeepInMines", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Centaurus was born on 26th January 2020
        '''Clicking on the warmcome header will change it into different color effects
        '''You can do hangouts with other buddies in ChatUp to call them in game
        '''You can use Wait for Somebody to Join when nobody&apos;s in game
        '''You can view your achievements &amp; progression in My Track
        '''You don&apos;t need to check for Centaurus updates or any other systematic stuffs because they are completely automated
        '''You can download your favorable or server required maps from MapDown instantly
        '''You can  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property didYouKnow() As String
            Get
                Return ResourceManager.GetString("didYouKnow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Dockbeta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Dockbeta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property docklands() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("docklands", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dockside() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dockside", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello admin, I&apos;m having several issues on game join.
        '''
        '''I get an unknown error while pressing the &apos;Join Game&apos; button on the main page: &quot;Player setup deployment failed.&quot; My network seems to be working fine, it was working fine in previous update, it&apos;s possibly an error.
        '''
        '''Please guide me how to fix this.
        '''You can take my email address for further contact: abcd@xyz.com.
        '''</summary>
        Friend ReadOnly Property exampleIssue() As String
            Get
                Return ResourceManager.GetString("exampleIssue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Factory2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Factory2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property forestraid() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("forestraid", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ghostcity() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ghostcity", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property hacked_humanplayer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hacked_humanplayer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property hacked_weapon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hacked_weapon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Haunted_Village() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Haunted_Village", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Homecoming() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Homecoming", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property humanplayer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("humanplayer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property igi2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("igi2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First of all, thank you for using Centaurus. You are warmly welcome here.
        '''
        '''In the first game launch, the Centaurus takes some backup &amp; writes some necessary files for a safe recovery in future, kindly let it proceed. Also, it sends your player information to improve Centaurus for the next update which you have accepted in our Code of Conduct.
        '''
        '''If you agree, then continue and you are ready to play.
        '''
        '''Let&apos;s Make I.G.I.-2 Great Again!.
        '''</summary>
        Friend ReadOnly Property information() As String
            Get
                Return ResourceManager.GetString("information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property JungleX() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("JungleX", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Libyan_Rendezvous() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Libyan_Rendezvous", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIT License
        '''
        '''Copyright (c) 2020 LinuX Man
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights
        '''to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        '''copies of the Software, and to permit persons to whom the Software is
        '''furnished to do so, subject to the following conditions:
        '''
        '''The above copyright noti [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mplocation1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mplocation1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mplocation2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mplocation2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mplocation3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mplocation3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NO_NAME_CITY() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NO_NAME_CITY", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pribois_villa_2018() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pribois_villa_2018", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Pribois_Villa_Night() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Pribois_Villa_Night", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Prison_Escape() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Prison_Escape", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property RainingMen() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RainingMen", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property redstone() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("redstone", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property robo_bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("robo_bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property robo_regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("robo_regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property sandstorm() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sandstorm", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Secret_Hideout() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Secret_Hideout", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are optionally but highly recommended to set a password for Centaurus to make it secure from others in your device except those who already knows your set password (if any).
        '''
        '''It is because other people in your computer may access it too and play, somehow if they does something bad, only you shall be responsible for any fatality. Therefore you are recommended to protect your launcher..
        '''</summary>
        Friend ReadOnly Property security() As String
            Get
                Return ResourceManager.GetString("security", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We are unable to synchronize your Centaurus to the server.
        '''YOU CAN CONTINUE USING OTHER FEATURES EXCEPT PLAYING THE MULTIPLAYER AFTER CLOSING THIS PAGE.
        '''
        '''The possible cause of this issue is listed along the possibility:
        '''
        '''  1. Your internet connectivity may be disturbed. (most possible)
        '''  2. Your IP range is yet blocked. (more possible)
        '''  3. The server is really down. (less possible)
        '''  4. Your Centaurus is not given access to the internet from the firewall. (least possible)
        '''
        '''Note: If you are gettin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property syncError() As String
            Get
                Return ResourceManager.GetString("syncError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Here is what could you do before applying a complaint form:
        '''
        '''  &gt; Try restarting your network connection by switching it off and on.
        '''  &gt; Check if your network is correctly connected to a network.
        '''  &gt; Go to RUN (Win+R), type &apos;cleanmgr&apos; and clean up the junk files.
        '''  &gt; The final solution: Change the I.G.I.-2 folder &apos;pc&apos; into &apos;pc1&apos; or something else and allow the Centaurus from your firewall.
        '''
        '''Fill up the form and submit if none of the above did work successfully. You can contact an active admin for help [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property syncSolution() As String
            Get
                Return ResourceManager.GetString("syncSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property THE_AIRFIELD_2019() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("THE_AIRFIELD_2019", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property timberland() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("timberland", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Ultimate_Warfare() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Ultimate_Warfare", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to turn on Waiting Mode? It is because probably somebody else might have already turned on waiting mode for another player to join. It is highly recommended to join and wait for at least 10 minutes before using this feature.
        '''
        '''Click &apos;Yes&apos; to ignore and start waiting, &apos;No&apos; to join game and see if somebody comes (recommended primarily), &apos;Cancel&apos; to do nothing &amp; quit from this box..
        '''</summary>
        Friend ReadOnly Property waitRecommendation() As String
            Get
                Return ResourceManager.GetString("waitRecommendation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property weapon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("weapon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property weapons() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("weapons", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property White_Wood() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("White_Wood", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property winterland() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("winterland", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
